#!/usr/bin/env python3
"""Modular Markup catalog / build system.

The folder structure under ``docs/TEMPLATES`` is the single source of truth.
Everything else -- every ``index.html``, the shared CSS in each folder, the
generated README tables and the release packages -- is derived from it.

Usage::

    python scripts/catalog.py generate     # (re)build indexes, CSS, README
    python scripts/catalog.py validate      # fail (exit 1) if anything is off
    python scripts/catalog.py package        # build per-pack ZIPs + manifest
    python scripts/catalog.py stats          # print catalog statistics

The heavy lifting is intentionally split into small, single-responsibility
pieces: *scanning* (disk -> model), *rendering* (model -> text) and *validation*
(disk vs. expected) never call into each other's concerns.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import zipfile
from collections.abc import Iterable, Iterator
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover - surfaced to the user with guidance
    sys.stderr.write(
        "PyYAML is required. Install it with 'pip install -r scripts/requirements.txt'.\n"
    )
    raise


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

REPO_ROOT = Path(__file__).resolve().parent.parent
LIBRARY_ROOT = REPO_ROOT / "docs" / "TEMPLATES"
METADATA_FILE = REPO_ROOT / "template-catalog.yml"
README_FILE = REPO_ROOT / "README.md"

#: Shared stylesheets copied verbatim into every generated folder so each folder
#: stays self-contained/portable (no relative ``../`` CSS paths are ever built).
SHARED_CSS = ("neo-brutalist.css", "neo-brutal-overrides.css")

#: Default heading/title for a generated index page.
DEFAULT_INDEX_TITLE = "\U0001F4DA Template Library"

#: Marks a file as machine-generated. Any ``index.html`` NOT carrying this class
#: (or the sentinel) is assumed to be a hand-authored app and is left untouched.
GENERATED_CLASS = 'class="page-index'
SENTINEL = (
    "<!-- Generated by scripts/catalog.py. Do not edit by hand: change the "
    "folder structure or template-catalog.yml and re-run 'catalog.py generate'. -->"
)

DESC_META_RE = re.compile(
    r'<meta\s+[^>]*name=["\']description["\'][^>]*content=["\'](.*?)["\']',
    re.IGNORECASE | re.DOTALL,
)
TITLE_RE = re.compile(r"<title[^>]*>(.*?)</title>", re.IGNORECASE | re.DOTALL)

INDEX_TEMPLATE = """<!DOCTYPE html>
<html lang="en" class="page-index neo-dark-doc">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="neo-brutalist.css" />
  <link rel="stylesheet" href="neo-brutal-overrides.css" />
  <title>{title}</title>
  {sentinel}
</head>
<body>

  <h1>{title}</h1>

  <h2 class="folder">HTML</h2>

  <p class="intro">
    <code>.html</code> files in this folder, excluding this index.
  </p>

  <div class="grid">
{html_cards}
  </div>

  <h2 class="folder">Folders</h2>

  <div class="grid">
{folder_cards}
  </div>

</body>
</html>
"""


# ---------------------------------------------------------------------------
# Metadata
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class PackConfig:
    name: str
    title: str
    public: bool = True


@dataclass
class Metadata:
    """Parsed view of ``template-catalog.yml`` (all keys are POSIX rel paths)."""

    packs: dict[str, PackConfig] = field(default_factory=dict)
    folders: dict[str, dict] = field(default_factory=dict)
    templates: dict[str, dict] = field(default_factory=dict)

    @classmethod
    def load(cls, path: Path = METADATA_FILE) -> "Metadata":
        if not path.exists():
            return cls()
        data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        packs = {
            name: PackConfig(
                name=name,
                title=(cfg or {}).get("title", prettify(name)),
                public=bool((cfg or {}).get("public", True)),
            )
            for name, cfg in (data.get("packs") or {}).items()
        }
        return cls(
            packs=packs,
            folders=dict(data.get("folders") or {}),
            templates=dict(data.get("templates") or {}),
        )

    def pack_config(self, name: str) -> PackConfig:
        return self.packs.get(name, PackConfig(name=name, title=prettify(name)))

    def is_public(self, pack: str) -> bool:
        return self.pack_config(pack).public


# ---------------------------------------------------------------------------
# Model
# ---------------------------------------------------------------------------


@dataclass
class Template:
    """A single ``.html`` template inside a folder."""

    path: Path  # absolute
    rel: str  # POSIX path relative to LIBRARY_ROOT
    name: str  # file name only
    title: str
    description: str
    source: str  # where the display text came from


@dataclass
class Folder:
    """A folder that participates in the catalog."""

    path: Path  # absolute
    rel: str  # POSIX path relative to LIBRARY_ROOT ("" for the root)
    name: str
    templates: list[Template] = field(default_factory=list)
    subfolders: list["Folder"] = field(default_factory=list)
    is_app: bool = False  # hand-authored app index -> never regenerated
    index_title: str = DEFAULT_INDEX_TITLE
    card_title: str = ""
    card_description: str = ""

    @property
    def pack(self) -> str:
        return self.rel.split("/", 1)[0] if self.rel else ""

    @property
    def is_root(self) -> bool:
        return self.rel == ""

    def walk(self) -> Iterator["Folder"]:
        """Yield this folder and every descendant (depth-first)."""
        yield self
        for sub in self.subfolders:
            yield from sub.walk()

    def all_templates(self) -> Iterator[Template]:
        for folder in self.walk():
            yield from folder.templates


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def prettify(name: str) -> str:
    """Turn a file/folder name into a human title (``quote-log`` -> ``Quote Log``)."""
    stem = Path(name).stem
    return stem.replace("-", " ").replace("_", " ").strip().title()


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def write_if_changed(path: Path, content: str) -> bool:
    """Write ``content`` (LF newlines) only when it differs. Returns True if written."""
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.write_text(content, encoding="utf-8", newline="\n")
    return True


def copy_if_changed(src: Path, dst: Path) -> bool:
    if src.resolve() == dst.resolve():
        return False
    data = src.read_bytes()
    if dst.exists() and dst.read_bytes() == data:
        return False
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_bytes(data)
    return True


def is_generated_index(path: Path) -> bool:
    """True if ``index.html`` is one of ours (safe to overwrite)."""
    if not path.exists():
        return True
    text = read_text(path)
    return GENERATED_CLASS in text or "scripts/catalog.py" in text


def extract_meta_description(text: str) -> str | None:
    match = DESC_META_RE.search(text)
    return match.group(1).strip() if match else None


def extract_title(text: str) -> str | None:
    match = TITLE_RE.search(text)
    if not match:
        return None
    return re.sub(r"\s+", " ", re.sub(r"<[^>]+>", "", match.group(1))).strip()


def html_escape(text: str) -> str:
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


# ---------------------------------------------------------------------------
# Scanning (disk -> model)
# ---------------------------------------------------------------------------


def _iter_children(folder: Path) -> tuple[list[Path], list[Path]]:
    """Return (html_files, subdirs) sorted case-insensitively, dotfiles skipped."""
    html_files: list[Path] = []
    subdirs: list[Path] = []
    for child in folder.iterdir():
        if child.name.startswith("."):
            continue
        if child.is_dir():
            subdirs.append(child)
        elif child.suffix.lower() == ".html" and child.name.lower() != "index.html":
            html_files.append(child)
    html_files.sort(key=lambda p: p.name.lower())
    subdirs.sort(key=lambda p: p.name.lower())
    return html_files, subdirs


def _build_template(path: Path, rel: str, meta: Metadata) -> Template:
    entry = meta.templates.get(rel, {})
    text = read_text(path)

    title = entry.get("title") or prettify(path.name)
    title_source = "metadata" if entry.get("title") else "filename"

    if entry.get("description"):
        description, desc_source = entry["description"], "metadata"
    elif (meta_desc := extract_meta_description(text)):
        description, desc_source = meta_desc, "html-meta"
    else:
        description, desc_source = f"{title} template.", "filename"

    source = desc_source if desc_source != "filename" else title_source
    return Template(
        path=path,
        rel=rel,
        name=path.name,
        title=title,
        description=description,
        source=source,
    )


def _apply_folder_metadata(folder: Folder, meta: Metadata) -> None:
    cfg = meta.folders.get(folder.rel, {})
    folder.card_title = cfg.get("title") or prettify(folder.name)
    folder.card_description = cfg.get("description") or f"{folder.card_title} folder."
    folder.index_title = cfg.get("index_title") or DEFAULT_INDEX_TITLE


def scan(folder_path: Path, meta: Metadata, rel: str = "") -> Folder:
    """Recursively build the catalog model rooted at ``folder_path``."""
    name = folder_path.name if rel else folder_path.name
    folder = Folder(path=folder_path, rel=rel, name=name)

    index_path = folder_path / "index.html"
    if rel and index_path.exists() and not is_generated_index(index_path):
        # Hand-authored app (e.g. animated-notes, mbox-viewer): treat as a leaf
        # card that links to its own index, never regenerate or descend into it.
        folder.is_app = True
        _apply_folder_metadata(folder, meta)
        return folder

    html_files, subdirs = _iter_children(folder_path)
    folder.templates = [
        _build_template(p, _join(rel, p.name), meta) for p in html_files
    ]
    for sub in subdirs:
        child = scan(sub, meta, _join(rel, sub.name))
        if _has_content(child):
            folder.subfolders.append(child)

    _apply_folder_metadata(folder, meta)
    return folder


def _join(rel: str, name: str) -> str:
    return f"{rel}/{name}" if rel else name


def _has_content(folder: Folder) -> bool:
    if folder.is_app or folder.templates:
        return True
    return any(_has_content(sub) for sub in folder.subfolders)


def visible_subfolders(folder: Folder, meta: Metadata) -> list[Folder]:
    """Subfolders shown in ``folder``'s index (premium packs hidden at the root)."""
    subs = folder.subfolders
    if folder.is_root:
        subs = [s for s in subs if meta.is_public(s.name)]
    return subs


# ---------------------------------------------------------------------------
# Rendering (model -> text)
# ---------------------------------------------------------------------------


def render_html_card(template: Template) -> str:
    return (
        f'    <a class="card orange" href="{template.name}">'
        f'<div class="title">{html_escape(template.title)}</div>'
        f'<div class="desc">{html_escape(template.description)}</div></a>'
    )


def render_folder_card(folder: Folder) -> str:
    return (
        f'    <a class="card purple" href="{folder.name}/index.html">'
        f'<div class="title">{html_escape(folder.card_title)}</div>'
        f'<div class="desc">{html_escape(folder.card_description)}</div></a>'
    )


def render_index(folder: Folder, meta: Metadata) -> str:
    html_cards = "\n".join(render_html_card(t) for t in folder.templates)
    folder_cards = "\n".join(
        render_folder_card(sub) for sub in visible_subfolders(folder, meta)
    )
    return INDEX_TEMPLATE.format(
        title=html_escape(folder.index_title),
        sentinel=SENTINEL,
        html_cards=html_cards,
        folder_cards=folder_cards,
    )


def render_readme_table(pack: Folder) -> str:
    """Markdown table of a pack's top-level templates and immediate subfolders."""
    rows = ["| File | Description |", "|------|-------------|"]
    for template in pack.templates:
        rows.append(f"| `{template.name}` | {template.description} |")
    for sub in pack.subfolders:
        rows.append(f"| `{sub.name}/` | {sub.card_description} |")
    return "\n".join(rows)


# ---------------------------------------------------------------------------
# CSS synchronization
# ---------------------------------------------------------------------------


def app_dirs(root: Folder) -> set[Path]:
    return {f.path.resolve() for f in root.walk() if f.is_app}


def find_canonical_css(name: str, excluded: set[Path]) -> Path | None:
    """Pick the canonical copy of ``name`` to propagate everywhere.

    Selection is by largest byte size, then lexicographic path. Size is used
    instead of modification time on purpose: git does not preserve mtimes, so an
    mtime-based rule would be non-deterministic across checkouts (picking a
    different file locally vs. in CI, causing commit churn) and could silently
    replace a complete stylesheet with a smaller, drifted copy. The largest copy
    is the most complete, which keeps every folder's appearance intact.

    Copies inside hand-authored app folders are ignored so an app-specific
    variant never becomes the library-wide source.
    """
    candidates = [
        p
        for p in LIBRARY_ROOT.rglob(name)
        if not any(_is_within(p, d) for d in excluded)
    ]
    if not candidates:
        return None
    candidates.sort(key=lambda p: (p.stat().st_size, str(p).lower()))
    return candidates[-1]


def _is_within(path: Path, parent: Path) -> bool:
    try:
        path.resolve().relative_to(parent)
        return True
    except ValueError:
        return False


def catalog_folders(root: Folder) -> list[Folder]:
    """Folders that receive a generated index (root + non-app folders)."""
    return [f for f in root.walk() if not f.is_app]


def sync_css(root: Folder) -> tuple[int, int]:
    """Copy canonical shared CSS into every generated folder.

    Returns (shared_files_synced, copies_written).
    """
    excluded = app_dirs(root)
    synced = 0
    copies = 0
    for name in SHARED_CSS:
        canonical = find_canonical_css(name, excluded)
        if canonical is None:
            continue
        synced += 1
        for folder in catalog_folders(root):
            if copy_if_changed(canonical, folder.path / name):
                copies += 1
    return synced, copies


# ---------------------------------------------------------------------------
# README generation
# ---------------------------------------------------------------------------


def _markers(pack: str) -> tuple[str, str]:
    return (
        f"<!-- TEMPLATE-CATALOG:{pack}:START -->",
        f"<!-- TEMPLATE-CATALOG:{pack}:END -->",
    )


def update_readme(root: Folder, meta: Metadata) -> tuple[bool, list[str]]:
    """Replace ``TEMPLATE-CATALOG`` marker blocks with generated tables.

    Only packs present on disk are updated; premium packs that are not checked
    out simply keep whatever content is already committed. Returns
    (changed, warnings).
    """
    if not README_FILE.exists():
        return False, ["README.md not found; skipping README generation."]

    text = read_text(README_FILE)
    warnings: list[str] = []
    packs = {sub.name: sub for sub in root.subfolders}

    for pack_name, pack_folder in packs.items():
        start, end = _markers(pack_name)
        if start not in text or end not in text:
            warnings.append(
                f"README has no {start} / {end} markers; skipping {pack_name} table."
            )
            continue
        table = render_readme_table(pack_folder)
        block = f"{start}\n{table}\n{end}"
        text = re.sub(
            re.escape(start) + r".*?" + re.escape(end),
            lambda _m, b=block: b,
            text,
            flags=re.DOTALL,
        )

    changed = write_if_changed(README_FILE, text)
    return changed, warnings


# ---------------------------------------------------------------------------
# Generation
# ---------------------------------------------------------------------------


@dataclass
class GenerateResult:
    indexes_written: int
    indexes_total: int
    css_synced: int
    css_copies: int
    readme_changed: bool
    warnings: list[str]


def generate(root: Folder, meta: Metadata) -> GenerateResult:
    css_synced, css_copies = sync_css(root)

    folders = catalog_folders(root)
    written = 0
    for folder in folders:
        if write_if_changed(folder.path / "index.html", render_index(folder, meta)):
            written += 1

    readme_changed, warnings = update_readme(root, meta)
    return GenerateResult(
        indexes_written=written,
        indexes_total=len(folders),
        css_synced=css_synced,
        css_copies=css_copies,
        readme_changed=readme_changed,
        warnings=warnings,
    )


# ---------------------------------------------------------------------------
# Statistics
# ---------------------------------------------------------------------------


@dataclass
class PackStats:
    name: str
    templates: int
    folders: int


def collect_stats(root: Folder) -> list[PackStats]:
    stats = []
    for pack in root.subfolders:
        templates = sum(1 for _ in pack.all_templates())
        folders = sum(1 for f in pack.walk() if f is not pack)
        stats.append(PackStats(pack.name, templates, folders))
    return stats


def format_stats(root: Folder, result: GenerateResult | None = None) -> str:
    lines: list[str] = []
    if result is not None:
        lines.append(f"Generated {result.indexes_total} index pages")
        lines.append("")

    pack_stats = collect_stats(root)
    for stat in pack_stats:
        lines.append(prettify(stat.name))
        lines.append("-" * max(len(stat.name), 8))
        lines.append(f"{stat.templates} templates")
        lines.append(f"{stat.folders} folders")
        lines.append("")

    total_templates = sum(s.templates for s in pack_stats)
    total_folders = sum(s.folders for s in pack_stats)
    lines.append(f"{total_templates} templates total")
    lines.append(f"{total_folders} folders")

    if result is not None:
        lines.append(f"{result.css_synced} CSS files synchronized")
        lines.append("README updated" if result.readme_changed else "README unchanged")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Validation (disk vs. expected)
# ---------------------------------------------------------------------------


class Validator:
    def __init__(self, root: Folder, meta: Metadata) -> None:
        self.root = root
        self.meta = meta
        self.errors: list[str] = []

    def error(self, message: str) -> None:
        self.errors.append(message)

    def run(self) -> list[str]:
        self._check_duplicates()
        for folder in catalog_folders(self.root):
            self._check_folder(folder)
        self._check_templates_have_titles()
        self._check_css_present()
        self._check_stale()
        self._check_readme_references()
        return self.errors

    def _check_duplicates(self) -> None:
        seen: dict[str, str] = {}
        for template in self.root.all_templates():
            if template.rel in seen:
                self.error(f"Duplicate catalog id/entry: {template.rel}")
            seen[template.rel] = template.rel

    def _check_folder(self, folder: Folder) -> None:
        index_path = folder.path / "index.html"
        if not index_path.exists():
            self.error(f"Missing generated index: {_display(index_path)}")
            return
        text = read_text(index_path)
        hrefs = re.findall(r'href="([^"]+)"', text)

        template_hrefs = [h for h in hrefs if not h.endswith("/index.html")
                          and not h.endswith(".css")]
        if len(template_hrefs) != len(set(template_hrefs)):
            self.error(f"Duplicate entries inside {_display(index_path)}")

        # Every referenced target must exist (no broken internal links).
        for href in hrefs:
            if href.startswith(("http://", "https://", "#", "mailto:")):
                continue
            target = (folder.path / href).resolve()
            if not target.exists():
                self.error(f"Broken link in {_display(index_path)} -> {href}")

        # Every on-disk template must appear in the index.
        listed = set(template_hrefs)
        for template in folder.templates:
            if template.name not in listed:
                self.error(
                    f"Template missing from catalog: {template.rel} "
                    f"(not listed in {_display(index_path)})"
                )
        # Every visible subfolder must be linked as folder/index.html.
        for sub in visible_subfolders(folder, self.meta):
            link = f"{sub.name}/index.html"
            if link not in hrefs:
                self.error(f"Folder link missing in {_display(index_path)} -> {link}")

    def _check_templates_have_titles(self) -> None:
        for template in self.root.all_templates():
            if not extract_title(read_text(template.path)):
                self.error(f"HTML has no <title>: {template.rel}")

    def _check_css_present(self) -> None:
        for folder in catalog_folders(self.root):
            for name in SHARED_CSS:
                if not (folder.path / name).exists():
                    self.error(f"Missing CSS {name} in {_display(folder.path)}")

    def _check_stale(self) -> None:
        for folder in catalog_folders(self.root):
            index_path = folder.path / "index.html"
            expected = render_index(folder, self.meta)
            if not index_path.exists() or read_text(index_path) != expected:
                self.error(f"Stale generated index: {_display(index_path)}")
        readme_stale, _ = _readme_is_stale(self.root, self.meta)
        if readme_stale:
            self.error("Stale README: run 'catalog.py generate'.")

    def _check_readme_references(self) -> None:
        if not README_FILE.exists():
            return
        text = read_text(README_FILE)
        refs = re.findall(r"\]\(([^)]+)\)", text)
        refs += re.findall(r'<img\s+[^>]*src="([^"]+)"', text)
        for ref in refs:
            ref = ref.split("#", 1)[0].split("?", 1)[0].strip()
            if not ref or ref.startswith(("http://", "https://", "mailto:", "#")):
                continue
            target = (REPO_ROOT / ref).resolve()
            if self._skip_absent_pack(target):
                continue
            if not target.exists():
                self.error(f"README references nonexistent file: {ref}")

    def _skip_absent_pack(self, target: Path) -> bool:
        """Ignore references into premium packs that are not checked out."""
        for pack, cfg in self.meta.packs.items():
            pack_dir = (LIBRARY_ROOT / pack).resolve()
            if not pack_dir.exists() and _is_within(target, pack_dir):
                return True
        return False


def _readme_is_stale(root: Folder, meta: Metadata) -> tuple[bool, str]:
    if not README_FILE.exists():
        return False, ""
    original = read_text(README_FILE)
    updated = original
    for pack in root.subfolders:
        start, end = _markers(pack.name)
        if start not in updated or end not in updated:
            continue
        block = f"{start}\n{render_readme_table(pack)}\n{end}"
        updated = re.sub(
            re.escape(start) + r".*?" + re.escape(end),
            lambda _m, b=block: b,
            updated,
            flags=re.DOTALL,
        )
    return updated != original, updated


def _display(path: Path) -> str:
    try:
        return str(path.resolve().relative_to(REPO_ROOT)).replace("\\", "/")
    except ValueError:
        return str(path)


# ---------------------------------------------------------------------------
# Packaging
# ---------------------------------------------------------------------------


@dataclass
class PackageInfo:
    name: str
    public: bool
    zip_path: Path
    templates: int
    folders: int
    bytes: int


def package(root: Folder, meta: Metadata, out_dir: Path, version: str | None) -> list[PackageInfo]:
    out_dir.mkdir(parents=True, exist_ok=True)
    infos: list[PackageInfo] = []
    stats = {s.name: s for s in collect_stats(root)}

    for pack in root.subfolders:
        zip_path = out_dir / f"{pack.name}.zip"
        size = _zip_folder(pack.path, zip_path)
        stat = stats[pack.name]
        infos.append(
            PackageInfo(
                name=pack.name,
                public=meta.is_public(pack.name),
                zip_path=zip_path,
                templates=stat.templates,
                folders=stat.folders,
                bytes=size,
            )
        )

    manifest = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "version": version,
        "packs": [
            {
                "name": info.name,
                "public": info.public,
                "zip": info.zip_path.name,
                "templates": info.templates,
                "folders": info.folders,
                "bytes": info.bytes,
            }
            for info in infos
        ],
    }
    (out_dir / "manifest.json").write_text(
        json.dumps(manifest, indent=2) + "\n", encoding="utf-8", newline="\n"
    )
    return infos


def _zip_folder(folder: Path, zip_path: Path) -> int:
    files = sorted(
        (
            p
            for p in folder.rglob("*")
            if p.is_file() and p.suffix.lower() != ".zip"
        ),
        key=lambda p: str(p).lower(),
    )
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as archive:
        for file in files:
            archive.write(file, arcname=str(file.relative_to(folder.parent)))
    return zip_path.stat().st_size


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _load_root(meta: Metadata) -> Folder:
    if not LIBRARY_ROOT.exists():
        sys.exit(f"Library root not found: {LIBRARY_ROOT}")
    return scan(LIBRARY_ROOT, meta)


def cmd_generate(args: argparse.Namespace) -> int:
    meta = Metadata.load()
    root = _load_root(meta)
    result = generate(root, meta)

    print(format_stats(root, result))
    for warning in result.warnings:
        print(f"warning: {warning}", file=sys.stderr)

    if args.no_validate:
        return 0

    # Re-scan so validation sees freshly written files.
    root = _load_root(meta)
    errors = Validator(root, meta).run()
    if errors:
        _report(errors)
        return 1
    print("Validation passed")
    return 0


def cmd_validate(args: argparse.Namespace) -> int:
    meta = Metadata.load()
    root = _load_root(meta)
    errors = Validator(root, meta).run()
    if errors:
        _report(errors)
        return 1
    print("Validation passed")
    return 0


def cmd_package(args: argparse.Namespace) -> int:
    meta = Metadata.load()
    root = _load_root(meta)
    infos = package(root, meta, Path(args.out), args.version)
    for info in infos:
        tag = "public" if info.public else "private (artifact only)"
        print(f"Packaged {info.name} -> {info.zip_path.name} ({info.bytes} bytes) [{tag}]")
    print(f"Manifest written to {Path(args.out) / 'manifest.json'}")
    return 0


def cmd_stats(args: argparse.Namespace) -> int:
    meta = Metadata.load()
    root = _load_root(meta)
    print(format_stats(root))
    return 0


def _report(errors: Iterable[str]) -> None:
    errors = list(errors)
    print(f"Validation FAILED with {len(errors)} error(s):", file=sys.stderr)
    for err in errors:
        print(f"  - {err}", file=sys.stderr)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="catalog.py",
        description="Generate and validate the Modular Markup template catalog.",
    )
    sub = parser.add_subparsers(dest="command", required=True)

    gen = sub.add_parser("generate", help="Regenerate indexes, CSS and README.")
    gen.add_argument(
        "--no-validate",
        action="store_true",
        help="Skip the validation pass after generating.",
    )
    gen.set_defaults(func=cmd_generate)

    val = sub.add_parser("validate", help="Validate the catalog (non-zero on failure).")
    val.set_defaults(func=cmd_validate)

    pkg = sub.add_parser("package", help="Build per-pack ZIPs and a manifest.")
    pkg.add_argument("--out", default=str(REPO_ROOT / "dist"), help="Output directory.")
    pkg.add_argument("--version", default=None, help="Version string for the manifest.")
    pkg.set_defaults(func=cmd_package)

    st = sub.add_parser("stats", help="Print catalog statistics.")
    st.set_defaults(func=cmd_stats)

    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
